- name: Install python-docker
  apt:
    name: python-docker

- name: Check if gitlab-runner repo is already present
  stat:
    path: /etc/apt/sources.list.d/runner_gitlab-runner.list
  register: gitlab_runner_repo

- name: Get Gitlab runner repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: /tmp/gitlab-runner.script.deb.sh
    mode: 0700
  when: gitlab_runner_runner.stat.isreg is defined

- name: Install Gitlab runner repository
  command: bash /tmp/gitlab-runner.script.deb.sh
  args:
    creates: "/etc/apt/sources.list.d/runner_gitlab-runner.list"
  become: true

- name: Install GitLab Runner
  apt:
    name: "gitlab-runner"
    state: "{{ gitlab_runner_package_state|default('present') }}"
  become: true

- name: Configurate gitlab-runner
  copy:
    src: "{{ gitlab_runner_config_path }}"
    dest: /etc/gitlab-runner/config.toml
  notify: restart gitlab-runner

# https://docs.docker.com/registry/recipes/mirror/
# https://hub.docker.com/_/registry
# https://docs.docker.com/registry/configuration/
# https://docs.docker.com/registry/deploying/
- name: Create registry proxy container
  docker_container:
    name: registry
    image: registry:2
    restart_policy: always
    volumes:
      - /var/registry-cache-container:/var/lib/registry
    ports:
      "192.168.42.1:6000:5000"
    env:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io

# https://docs.gitlab.com/runner/install/registry_and_cache_servers.html#install-your-own-cache-server
- name: Create object storage container
  docker_container:
    name: minio
    image: minio/minio:latest
    restart_policy: always
    command: server /data
    volumes:
      - /var/minio/data:/data
    ports:
      "192.168.42.1:9000:9000"
    env:
      MINIO_ACCESS_KEY: "{{ gitlab_runner_minio_access_key }}"
      MINIO_SECRET_KEY: "{{ gitlab_runner_minio_secret_key }}"

- name: Create gitlab-runner minio bucket
  file:
    path: /var/minio/data/gitlab-runner
    state: directory
